spring.application.name=microservicio-resenas
server.port=8090

spring.datasource.url=jdbc:h2:file:./data/resenasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuracion JPA / Hibernate: crea y actualiza el esquema automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# URLs de los microservicios que consume via Feign
libros.url=${LIBROS_URL:http://localhost:8081}
usuarios.url=${USUARIOS_URL:http://localhost:8082}

springdoc.swagger-ui.path=/swagger-ui.html
